translated: issue #4
docschina/ecma262-old pull request #31
Opened 2017-12-23 14:10 UTC by realywithoutname

issue #4

2017-12-24 03:32 UTC, hijiangtao requested changes
除中英文混排方案需要决定外，其余意见在对应行位置已标明。

2017-12-24 03:32 UTC, hijiangtao commented on translated/issues-4.html
> +  <p>ECMAScript是一门在宿主环境执行计算以及操作可计算对象的面向对象编程语言。这里定义的ECMAScript并不打算有自给自足的计算；事实上，该规范并没有规定外部数据的输入或者计算结果的输出。相反，我们期望ECMAScript程序的计算环境不仅提供本规范中描述的对象和能力，还能特定环境对象，本规范除了说明这些对象应该提供可被ECMAScript程序访问的某些属性，调用的某些方法外，
「还能特定环境对象」→「还包括特定环境对象」

2017-12-24 03:32 UTC, hijiangtao commented on translated/issues-4.html
> +  <p>ECMAScript最初被设计为一门脚本语言，但是现在已经作为一门通用的编程语言被广泛应用。脚本语言是指一种用于操作，定制，自动化现有系统能力的编程语言。在这样的系统中，通过用户接口使的有用的功能变得可用，而脚本语言就是暴露这些功能给程序控制的机制。以这样的方式，来完成脚本语言能力的系统被称作提供对象和功能的宿主环境。脚本语言的目的是专业和非专业的程序员都可以使用。</p>
1. 「脚本语言」em标签应该保留
2. 「在这样的系统中...（至结尾）」→「在这样的系统中，通过用户界面已经可以使用有用的功能，而脚本语言是将这些功能暴露给程序控制的机制。 通过这种方式，现有的系统被称为提供对象和能力的宿主环境，从而完成了脚本语言的功能。 脚本语言是供专业和非专业程序员使用的。」

2017-12-24 03:32 UTC, hijiangtao commented on translated/issues-4.html
> +  <p>ECMAScript最初被设计为<em> Web 脚本语言</em>，提供了一种让网页更加富有生机的机制，并能够进行部分基于Web B/S架构的服务器端计算。ECMAScript现在用于多种宿主中提供核心脚本能力。因此该文档描述的是除特定宿主环境外的语言核心。</p>
「ECMAScript现在用于多种宿主中」→「ECMAScript现在被用于在多个宿主环境中」

2017-12-24 03:32 UTC, hijiangtao commented on translated/issues-4.html
> +  <p>ECMAScript用法已经远超出了简单脚本，现在被用于很多不同的环境和规模的全方位编程任务。随着ECMAScript不断扩大使用范围，其功能和设施也得到了扩展。ECMAScript现在成为了一个功能齐全的通用编程语言。</p>
1. 「设施」→「能力」
2. 「不断扩大适用范围」→「的使用扩大」

2017-12-24 03:32 UTC, hijiangtao commented on translated/issues-4.html
> +  <p>ECMAScript的一些能力类似于其他编程语言中，特别是C, Java&trade;, Self, 以及Scheme，如下所述：</p>
「Scheme，如下所述」→「如下所述的一些 Scheme」

2017-12-24 03:32 UTC, hijiangtao commented on translated/issues-4.html
> +  <p>Gosling, James, Bill Joy and Guy Steele. <i>The Java<sup>&trade;</sup> Language Specification</i>. Addison Wesley PublishingCo., 1996.</p>
原文不做修改

2017-12-25 13:01 UTC, realywithoutname commented on translated/issues-4.html
> +  <p>ECMAScript用法已经远超出了简单脚本，现在被用于很多不同的环境和规模的全方位编程任务。随着ECMAScript不断扩大使用范围，其功能和设施也得到了扩展。ECMAScript现在成为了一个功能齐全的通用编程语言。</p>
As the usage of ECMAScript has expanded, so has the features and facilities it provides. 
随着ECMAScript使用范围的扩大，其功能和能力也得到了扩展

2017-12-25 13:01 UTC, realywithoutname commented on translated/issues-4.html
> +  <p>ECMAScript最初被设计为一门脚本语言，但是现在已经作为一门通用的编程语言被广泛应用。脚本语言是指一种用于操作，定制，自动化现有系统能力的编程语言。在这样的系统中，通过用户接口使的有用的功能变得可用，而脚本语言就是暴露这些功能给程序控制的机制。以这样的方式，来完成脚本语言能力的系统被称作提供对象和功能的宿主环境。脚本语言的目的是专业和非专业的程序员都可以使用。</p>
A scripting language is intended for use by both professional and non-professional programmers.
脚本语言的目的是使专业和非专业程序员都能够使用。

这样会不会好点？

2017-12-28 13:02 UTC, realywithoutname commented
@hijiangtao @soulhat 看这个pr是否可以被合并。

2017-12-29 00:48 UTC, hijiangtao commented
除以上提到的 review 意见没有其他意见了。如果修改中没有存在歧义的地方，我觉得就没问题了；如有歧义可以单挑出来讨论。

2017-12-29 01:01 UTC, hijiangtao approved these changes

2017-12-31 07:49 UTC, merged