translated: issue #9
docschina/ecma262-old pull request #34
Opened 2018-01-01 12:16 UTC by realywithoutname

2018-01-05 09:24 UTC, hijiangtao reviewed
校对了原文 L1-L51 （对应译文 L1-L50）的内容

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +  <p>本规范中算法操作每个具有相关类型的值。可能的值类型直接定义在本章节中。这些类型进一步分为 ECMAScript 语言类型与规范类型。</p>
1. 操作 -> 操纵/控制

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +  <p>在本规范中，&ldquo;Type(_x_)&rdquo;表示法是&ldquo;the <dfn id="type">type</dfn> of _x_&rdquo;的简写， 其中&ldquo;type&rdquo;指的是在本章节中定义的 ECMAScript 语言类型与规范类型。当一个值使用术语&ldquo;empty&rdquo;命名值时，它相当于说&ldquo;没有任何类型的值(
之前章节翻译的时候针对保留原文用的是 html 标签的方式，如果 no value of any type 需要保留建议与之前保持一致。

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +    <p>一个 <dfn>ECMAScript 语言类型</dfn>对应那些 ECMAScript 程序员在 ECMAScript 语言中直接使用的值。 ECMAScript 语言类型有 Undefined, Null, Boolean, String,Symbol, Number, Object。 一个<dfn>ECMAScript 语言值</dfn>是指拥有 ECMAScript 语言类
1. 拥有 ECMAScript 语言类型特点 -> 拥有一个 ECMAScript 语言类型特点

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>Boolean 类型表示具有 `true` 和 `false` 两个值的逻辑实体。</p>
1. 逻辑实体 -> 一个逻辑实体

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>String 类型是零个或多个 16 位无符号整数值（&ldquo;元素&rdquo;）的所有有序序列的集合，最大长度为 2<sup>53</sup>-1 个元素。字符串类型通常用于表示正在运行的 ECMAScript 程序中的文本数据，在这种情况下，String中的每个元素都被视为一个 UTF-16 <abbr title="code unit">码元</abbr>。 每个元
1. 句号后面不需要添加空格
2. 即 16-bit 值 -> 例如，十六位的值

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +        <p>这种设计背后的理由是尽可能的保持 String 的实现简单和高效。 如果 ECMAScript 源文本符合 Normalized Form C，只要它们不包含任何 Unicode 转义序列，则字符串字面量保证也是标准化的。</p>
1. Normalized Form C 没查到具体所指，如果有通用称呼，之后可以翻译成中文

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +          两个码元，第一个码元 _c1_ 范围为 0xD800 到 0xDBFF，第二个码元 _c2_ 范围为 0xDC00 到 0xDFFF， 这样的两个码元，被称为<attr title="surrogate pair">代理对</attr>， 被解释为一个值为 (_c1_ - 0xD800) &times; 0x400 + (_c2_ - 0xDC00) + 0x10000 的码
1. 两个码元 -> 两个码元序列
2. (See <emu-xref href="#sec-utf16decode"></emu-xref>) 在翻译中丢失

2018-01-05 09:24 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>在本规范中，短语"the string-concatenation of _A_,_B_,..."表示字符串代码单元的序列是每个参数的代码单元的连接。</p>
括号内文字未做翻译

2018-01-07 08:52 UTC, hijiangtao reviewed
校对 L51-L203 部分

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>Symbol 类型是所有可以用于作为 Object 属性的 key 的非字符串值的集合。(<emu-xref href="#sec-object-type"></emu-xref>).</p>
1. 注意中英文标点
2. 这样修改可能会更加通顺一些：Object 属性的 key -> Object 属性 key 值

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>每个 Symbol 值永远地保持一个与之关联的叫做 [[Description]] 的值（它要么是 undefined 要么是一个 String 值）。</p>
1. 原文 undefined 有强调符号标注

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +        <h1>著名 Symbol</h1>
1. Well-Known 翻译成“众所周知的”可能会更好，下文同理

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +        <p>著名 Symbol 是那些被本规范中算法明确引用的内置 Symbol 值。它们通常被用作属性的 key，这些 key 的值为规范的算法提供了一种扩展。除非另有说明，著名 Symbol 的值被所有域(<emu-xref href="#sec-code-realms"></emu-xref>)共享。</p>
1. 为规范的算法提供了一种扩展 -> 作为规范算法的扩展点

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +        <p>在本规范内，一个著名 Symbol 值通过形如 form@@name 的形式被引用，这里的 &ldquo;name&rdquo; 是表 <emu-xref href="#table-1"></emu-xref> 列出的值之一。</p>
1. form 多余，删除

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +                  名称
1. 名称 -> 规范名称

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +                  一个Boolean值，如果为 true， 表示一个对象应该被 <emu-xref href="#sec-array.prototype.concat">`Array.prototype.concat`</emu-xref> 扁平化的加入到元素中。
1. 元素 -> 数组元素

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +                  一个正则表达式方法，它返回正则表达式匹配到在字符串中的索引。 由<emu-xref href="#sec-string.prototype.search">`String.prototype.search`</emu-xref>方法调用。
1. 匹配到 -> 匹配到的内容

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +                  一个字符串值属性，用于表示对象在创建时的默认字符串描述。通过内置方法 <emu-xref href="#sec-object.prototype.tostring">`Object.prototype.toString`</emu-xref> 访问。
1. 第一句话可以翻译为如下二选一的形式：“用于创建对象的默认字符串描述的 String 值属性” 或者 “一个 String 值属性，用于创建对象的默认字符串描述” （因为 String 此处为大写，所以应该是特指，建议不翻译为“字符串”，保留原文）

2018-01-07 08:52 UTC, hijiangtao commented on translated/issues-9.html
> +                  一个对象值属性，其自身和继承的属性名是从相关对象非在 `with` 环境绑定的属性名。
1. 非在 `with` 环境绑定的属性名。 -> 的 `with` 环境绑定中排除的属性名。

2018-01-07 12:41 UTC, realywithoutname commented on translated/issues-9.html
> +        <p>这种设计背后的理由是尽可能的保持 String 的实现简单和高效。 如果 ECMAScript 源文本符合 Normalized Form C，只要它们不包含任何 Unicode 转义序列，则字符串字面量保证也是标准化的。</p>
一种转换字符为标准化字符的方式。http://unicode.org/reports/tr15/

2018-01-07 12:46 UTC, realywithoutname commented on translated/issues-9.html
> +        <h1>著名 Symbol</h1>
“众所周知的Symbol“ 作为标题感觉有些长，但是更好理解，但是放到具体的语句中有一些歧义。比如：
众所周知的 Symbol 是那些被本规范中算法明确引用的内置 Symbol 值。它们通常被用作属性的 key，这些 key 值作为规范算法的扩展点。

2018-01-07 14:09 UTC, hijiangtao commented on translated/issues-9.html
> +        <h1>著名 Symbol</h1>
我认为放在句中“众所周知”和“著名”的歧义感应该类似，都存在不好理解的可能。这个应该通过语序来调整，或者更合适的翻译来替代，例如“被人广泛了解的”等。或者，简单来看，“有名”，“出名”，“出众”等词是否可行？供参考。感觉翻译后不管哪个形式结合到上下文都有些奇怪。

2018-01-26 09:46 UTC, hijiangtao requested changes
L204-L230 校对工作

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>Number 类型有 18437736874454810627 (即，<emu-eqn>2<sup>64</sup>-2<sup>53</sup>+3</emu-eqn>)个值，表示双精度 64 位格式的 IEEE 754-2008 值由 IEEE 二进制浮点数标准规定，除了 9007199254740990 (即，<emu-eqn>2<sup>53</sup>-2</emu-
1. "表示双精度 64 位格式的 IEEE 754-2008 值由 IEEE 二进制浮点数标准规定" 前后半句的语序可以调整一下；
2. NaN 是由强调符号围绕，而不是代码块符号，后文同理；

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +        <p>一个可被观察的 ArrayBuffer(见<emu-xref href="#sec-arraybuffer-objects"></emu-xref>) 或 SharedArrayBuffer(见<emu-xref href="#sec-sharedarraybuffer-objects"></emu-xref>) 中存入一个Number值之后的位模式没有必要与 ECMASc
该句不通顺，我的翻译为“在一个 Number 数值被存入之后，在一个 ArrayBuffer 或一个 SharedArrayBuffer 中可能观察到的位模式不一定和 ECMAScript 实现所使用的那个 Number 数值的内部表示相同。”

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>还有另外两个特殊的值，叫做<abbr title="positive Infinity">*正无穷*</abbr>和<abbr title="*negative Infinity*">*负无穷*</abbr>。 为了简洁起见，这些值分别由符号 `+&infin;` 和 `-&infin;` 表示。（请注意，这两个无限数值由程序表达式 `+Infinity`（或 `Infinit
“无限” -> “无穷”

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>除了 3 个特殊值，其他 18437736874454810624（即，<emu-eqn>2<sup>64</sup>-2<sup>53</sup></emu-eqn>）个值称为有限值。 其中一半为正数，一般为负数；每个有限正数存在相同大小的对应负数。</p>
1. 原文没有出现“除了 3 个特殊值”的对应英文？
2. Number 如果为大写应该是特指，需要保留原文

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>其中 _s_ 为 +1 或 -1，_m_ 是一个小于 2<sup>53</sup> 大于等于 2<sup>52</sup> 的整数，_e_ 是从 -1074 到 971 的整数。</p>
“是一个小于 2<sup>53</sup>”后面应该加一个连词“但”

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>注意，大小不大于 2<sup>53</sup> 的所有正整数和负整数可以在数字类型中表示（实际上，整数 0 具有两个表示，`+0` 和 `-0`）。</p>
“数字” -> “Number”

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>如果一个有限的数值非零且用来表达它（上文两种形式之一）的整数 m 是奇数，则该数值有<em><abbr title="odd significand">奇数意义</abbr></em>。否则，它有<em><abbr title="even significand">偶数意义</abbr></em>。</p>
“m” -> "_m_"

2018-01-26 09:46 UTC, hijiangtao commented on translated/issues-9.html
> +      <p>在本规范中，当 _x_ 表示一个精确的非零实数数学量（甚至可以是无理数，比如&pi;）时，&ldquo;the Number value for _x_&rdquo; 意为，以下面的方式选择一个 Number 值。考虑 Number 类型中除了 `-0` 和两个被加入在数值类型中但不可呈现的值，2<sup>1024</sup> (<emu-eqn>+1 &times; 2<su
1. "&ldquo;the Number value for _x_&rdquo;" 部分多余，要么在 `_x_` 部分添加定语，要么保持现状，该部分可以删掉；
2. 数字还原为 “Number”；

2018-01-26 09:51 UTC, hijiangtao commented
校对过程中我在想一个可以讨论的地方，类似 Number 或者 Object 这种特指是否翻译：翻译的理由因为他们中部分翻译成中文其实不会存在歧义，且如果类似 Object 的所指都不翻译会造成文章阅读不顺畅；不翻译的原因也是因为他们是特指，已经译文对这些词汇也有保留。但是我认为全文需要统一，如果部分翻译部分保留（比如标题中才保留）不太符合翻译规范。

2018-01-26 10:30 UTC, dear-lizhihua commented on translated/issues-9.html
>    <!-- es6num="6.1" -->
行数最好还是保持一致，这样 git 对比不会有问题

2018-01-28 07:50 UTC, realywithoutname commented on translated/issues-9.html
>    <!-- es6num="6.1" -->
没注意

2018-02-11 04:18 UTC, hijiangtao reviewed
校对至315行。

2018-02-11 04:18 UTC, hijiangtao commented on translated/issues-9.html
> +          <em>访问器属性</em>关联 key 值和一个或两个访问器函数以及一组值为 Boolean 类型的特性。访问器函数用于存储或检索与属性相关联的 ECMAScript 语言值。
属性 -> 该属性

2018-02-11 04:18 UTC, hijiangtao commented on translated/issues-9.html
> +        <p>在本规范中特性用来定义和解释对象属性的状态。数据属性关联表<emu-xref href="#table-2"></emu-xref>中列出的一个 key 值的特性。</p>
后一句：数据属性将 key 值与表中<emu-xref href="#table-2"></emu-xref>列出的特性关联。

2018-02-11 04:18 UTC, hijiangtao commented on translated/issues-9.html
> +          访问器属性关联表<emu-xref href="#table-3"></emu-xref>中的列出一个值。
中英文翻译行数不一致。

2018-03-09 11:54 UTC, merged

2018-03-09 12:26 UTC, realywithoutname commented on translated/issues-9.html
> +      <p>在本规范中，当 _x_ 表示一个精确的非零实数数学量（甚至可以是无理数，比如&pi;）时，&ldquo;the Number value for _x_&rdquo; 意为，以下面的方式选择一个 Number 值。考虑 Number 类型中除了 `-0` 和两个被加入在数值类型中但不可呈现的值，2<sup>1024</sup> (<emu-eqn>+1 &times; 2<su
“the Number value for x” 这部分是在算法中会用到的，有实际意义的。我认为应该保留